eps_start: 1.0
eps_end: 0.1
eps_stable: 500000

rms_prop_lr: 0.00025
gradient_momentum: 0.95
squared_momentum: 0.95

adam_lr: 0.0005

batch_size: 32
replay_memory_size: 500000
replay_start_size: 50000

agent_history_lenght: 4
update_frequency: 4
update_target_network: 10000
discount_factor: 0.99

nr_episodes: 1000000
epoch_size: 25000

target_network_path: "TargetNetwork3"
q_network_path: "QNetwork3"
extra_params_path: "Parameters3"

ep_length: 1000